### ISSUE TITLE
Undo & Redo functionality

### ISSUE THREAD

**Issue by smotched** [webstudio-is/webstudio-designer#1]
Currently if the webstudio designer incorrectly places an item at the top of the screen you have to go find that element and remove it. A simple undo would be useful.

This is important early in alpha because the webstudio designer is going to be making a lot more mistakes on drop areas early on.

**Comment by kof** [comment]
Absolutely, some of the most foundational features!

**Comment by kof** [comment]
ups, got a duplicate #8
