### ISSUE TITLE
Update to the Menu Item component, necessary for token states. 

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#1009]
The Menu Item component has been updated in figma.
<img width="601" alt="Screenshot 2023-02-12 at 2 31 29 PM" src="https://user-images.githubusercontent.com/86495896/218341203-40548ad4-eb23-455e-82c0-7186cfaa2b15.png">

Radix parity updates:
- changed name of "show icon space" property to "Checkbox Item" 
- changed name of variant "set" to "checked"
- changed name of variant "normal" to "normal/unchecked"
- changed name of state "hover/focus" to "highlighted"

Updates necessary for token states:
- "dot inherited" variant deleted becuase not needed
- "dot preset" variant deleted because not needed
- "checked and set" variant added (check mark is blue) Explanation below ↓

<img width="192" alt="Screenshot 2023-02-12 at 2 43 01 PM" src="https://user-images.githubusercontent.com/86495896/218341698-7b4c1ef6-59bc-4290-8f0b-e30447c09954.png">
These two variants in the screenshot are exclusively used to represent states in the states menu, the menu that shows on all tokens and allows the user to style a state on that token.

"set dot" (blue dot) indicates that there are styles applied to the state. This helps the user quickly see which states in the menu are styled and which aren't.

"checked and set" (blue check) indicates that there are styles applies to the state AND the user has selected that state (meaning it shows in the style source input). It's a combination between the "set dot" variant and the "checked" variant.

I hope that makes sense and gives you the info you need to update this component. I'm happy to answer any questions.

**Comment by kof** [comment]
@rpominov please estimate how much time it is to implement those changes and if the states fit well with radix's components

**Comment by rpominov** [comment]
> changed name of "show icon space" property to "Checkbox Item"
> changed name of variant "set" to "checked"
> changed name of variant "normal" to "normal/unchecked"
> changed name of state "hover/focus" to "highlighted"

These names look good. And I did't use the old names in code, so no work here

-------------

For the "set dot" and "checked and set" there are no corresponding states in Radix. I would implement it like this:

- we already allow to set arbitrary icon: `<DropdownMenuCheckboxItem icon={<Icon />}`
- expose `<MenuSetDotIcon>` and `<MenuCheckedAndSetIcon>` icons that have blue color

So in code it will be used like this: `<DropdownMenuCheckboxItem icon={<MenuSetDotIcon />}`

Exposing these icons should take 10 minutes

**Comment by kof** [comment]
Great lets do it this week, as @TrySound will start working in the next days on states
