### ISSUE TITLE
Support different storage options

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio-designer#114]
Users be able to self-host Webstudio with local database, but we still able to deploy the same codebase to edge for the hosted version.

## Solution
- [ ] Introduce a new environment variable that defines the storage type. 
For example: `STORAGE_TYPE = edge|database`
Based on the value of this variable, we need to query the right place for the project's tree. 
Currently `Cloudflare Workers with KV store` for `edge` and `PostgreSQL`  for `database` is in scope.
- [ ] Rewrite the function of `loadById` (and others) to handle each cases.

**Comment by kof** [comment]
KV Store is only a cache layer for a quick access from the worker, right?

To populate the cache, worker will make a fetch request to the designer server that holds connection to the database. That server has Rest API right now that worker can already use.

**Comment by kof** [comment]
Got it, so you basically need db.canvas.loadPreviewData() and put it into kv, from the designer server

**Comment by andrasbacsai** [comment]
I think this is not needed anymore as we solved it, but in a different way.
