### ISSUE TITLE
Body HTML tag

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#143]
How do we want to handle the body HTML tag? Can users change the styles on the tag?

In Webflow the body is always the top level parent in the Navigator panel. It can be given a class but doesn't need to.

It's useful to be able to select the body element for things like setting the typography defaults for the project, or changing the body to overflow:hidden to prevent page scrolling when a modal is open, for example.

An advantage to copying Webflow in this case is that the WF users we are trying to convert will already have habits for what they do with the Body element.

**Comment by kof** [comment]
If we wanted to map html more closely, we would even have html, head, meta etc, but at this point the question is what would it give us to do it this way? Technically we can put styles on the root node, even if its not body. Is there anything body gives us that can't be done on the root node (I don't think so)?

I see the root node as a sort of entire page content, while it can be moved from one page to another by moving a single root instance.

We could add body to the tree and make it sort of a special thing that can't be moved etc, I wonder though if its really worth it.

**Comment by kof** [comment]
On the other hand we could just turn that root instance we have now into a body
