### ISSUE TITLE
Searchbar for CSS properties

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#15]
### Discussed in https://github.com/webstudio-is/webstudio/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **mo-lab** March 22, 2022</sup>
hi loved the product
I think a search bar for CSS attributes might be helpful
![Capture](https://user-images.githubusercontent.com/55297854/159508882-ae4a878d-63ef-4a12-9f49-875a697620e3.JPG)
right in this section
</div>

**Comment by smotched** [comment]
Might make sense to add discussions to this repo as well, to keep discussions organized.

**Comment by kof** [comment]
I am afraid of getting lost between 2 sources of discussions, lets see if we need to change that in the future, right now, its not that hard

**Comment by kof** [comment]
search released! Please give it a try to see if it works for you
