### ISSUE TITLE
Watch packages in yarn dev

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#162]
Since we moved sdk to monorepo, sdk is not being watched by remix server and basically we have to restart it to make it see the changes,

This example uses tsup which uses esbuild, I guess we could do that, right?

https://github.com/remix-run/remix/blob/main/examples/turborepo-vercel/packages/ui/package.json#L12

**Comment by kof** [comment]
Wasn't this fixed?

**Comment by SaraVieira** [comment]
yap, this is done! closing
