### ISSUE TITLE
Connect new asset manager to R2

### ISSUE THREAD

**Issue by SaraVieira** [webstudio-is/webstudio-designer#166]
Our new asset manager supports anything that has S3 API support and we want to use R2 for file storage it seems to have S3 API for both `PutObject` and `deleteObject`

Steps:

- [x] Create webstudio Cloudflare account nd invite me and @andrasbacsai 
- [ ] Make asset manager work locally with R2
- [ ] Add all env variables in vercel and turn it on

**Comment by andrasbacsai** [comment]
@kof We need to set up the payment method/credit card details in CF to be able to use R2. Could you please do it?

We will probably don't get over the free tier, but it is mandatory to have these details set before we can use R2.
![image](https://user-images.githubusercontent.com/5845193/180392554-8011e903-5052-4f0a-8c17-ceb066f69d28.png)

**Comment by kof** [comment]
I think I did, no?

**Comment by kof** [comment]
@andrasbacsai done

**Comment by kof** [comment]
wasn't this fixed?

**Comment by SaraVieira** [comment]
Yap! This is been done!
