### ISSUE TITLE
DnD primitive improvements

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#175]
We need to make some improvements to the DnD primitive developed in #149

 - [x] Remove touch and keyboard listeners from useMove https://github.com/webstudio-is/webstudio-designer/pull/149#discussion_r926713532
 - [x] Add a demo with horizontal shift
 - [x] Fix spacing in the list demos
 - [ ] Highlight current drop target somehow in demos
 - [x] Add a demo when a drop target expands on hold
 - [x] Add unit tests
 - [x] Move technical descriptions from the PR to a readme file in the primitive
 - [ ] Add a demo where a copy of a drag item is being dragged visually rather than moving an empty cursor
 - [x] If the user releases the mouse button while outside of the browser window, the UI shouldn't get stuck in the "dragging" state
 - [x] Pressing "esc" should cancel the active drag
 - [x] Make sure test-cases.md is up to date and complete regarding DnD

**Comment by rpominov** [comment]
While I'm trying to figure out what should live in the iframe, I came up with this table:

| Needs access to: |  Drop targets DOM | Drag items DOM | Scroll events |
|-|-|-|-|
| `useDrag` | | V | |
| `useDropTarget` | V | | V |
| `usePlacement` | V | | V |
| `useAutoScroll` | V (assuming scroll container is in targets DOM) | | |

Which made me realise that `useDropTarget` and `usePlacement` have very similar concerns. Might make sense to merge them to a single hook.

**Comment by rpominov** [comment]
Another though: we probably shouldn't used the probe geometry directly for the placement indicator. This doesn't work well. Instead, use probe only to determine children direction when there're less than 2 children.

And to determine placement indicator geometry rely on target and its children rects. This will allow to, for example, always show the placement indicator neatly between two children at the same distance from both of them.

**Comment by kof** [comment]
> And to determine placement indicator geometry, rely on the target and its children's rects. This will allow to, for example, always show the placement indicator neatly between two children at the same distance from each of them.

it does sound like its more complexity, but if there is no other way, I guess ...

**Comment by rpominov** [comment]
> it does sound like its more complexity, but if there is no other way, I guess ...

Need to try, but it doesn't seem that complex.

I actually worry more about weird behaviour of the probe in edge cases, and workarounds we'd have to add to account for that.

**Comment by rpominov** [comment]
> Add a demo with horizontal shift
> Add a demo when a drop target expands on hold

After tree is moved to design system it will act as a demo for these features
