### ISSUE TITLE
Ability to change the units of value

### ISSUE THREAD

**Issue by piyusharorawork** [webstudio-is/webstudio-designer#18]
Lets say I want to change the height value from px to vh . 
Probably a drop down for unit will be helpful here 

![image](https://user-images.githubusercontent.com/31386968/160909666-acc8fa9e-cc69-47d1-b6ce-16d22e0e232c.png)

**Comment by kof** [comment]
Yep, right now you have to type it, but we absolutely need  a dropdown there as an option.

**Comment by kof** [comment]
was done
