### ISSUE TITLE
Drop indicators

### ISSUE THREAD

**Issue by smotched** [webstudio-is/webstudio-designer#2]
Although there is an obvious hierarchy in the tree section, there's no indicator where the element will be placed when dropped (above, below, inside)

A simple horizontal line indicating where the element will be dropped would be useful!

**Comment by kof** [comment]
Yes! or a tree structure in a sidebar showing where its going to drop, like webflow does it.

**Comment by smotched** [comment]
It might be best to put the tree on the bottom like [they do here](https://shuffle.dev/editor?project=f23d0f955ebca6e16a219568fee991a5520f3e63) to make the hierarchy viewable while working on the selected component

**Comment by smotched** [comment]
It might be best to put the tree at the bottom like [they do here](https://shuffle.dev/editor?project=f23d0f955ebca6e16a219568fee991a5520f3e63) to make the hierarchy viewable while working on the selected component

**Comment by kof** [comment]
I just released tree preview in the right sidebar, feedback is very welcome!

**Comment by kof** [comment]
Created a separate issue for another problem - being able to drop instances where they don't belong https://github.com/webstudio-is/webstudio-designer/issues/7

**Comment by kof** [comment]
https://user-images.githubusercontent.com/52824/159981041-9d1ffa68-c02b-4807-97c9-0a4355b8e65a.mp4

Let me know if this is not good and we will reopen or create a new one with more details

**Comment by smotched** [comment]
Looks great @kof...what plans do you have for the right menu, I see you left ample room for other tab items, would it be more consistent if we move the tree to a tab on the right and simply activate it during drag instead of having 2 trees? In some instances we can even see 2 trees on the screen at the same time

<img width="1137" alt="Screen Shot 2022-03-24" src="https://user-images.githubusercontent.com/91352309/160027594-a74339f8-0d26-4f8d-83e1-d6da4a6d2a1c.png">

Side note, this addition does break the site on ff when dragging, not sure how much you're thinking about browser compatibility at this stage. Couldn't figure out what's breaking it though 🤔

**Comment by kof** [comment]
I am curious how you made both sidebars appear at the same time! Left sidebar goes away when you interact with canvas, because it overlaps it. Right sidebar takes always that space, that's why I showed it there. I was also thinking it would be better to have it consistently in one place, but to do so we need to change how left sidebar is behaving with regards to the canvas. It is easy to move any time though.

**Comment by kof** [comment]
Well the alternative is to move to the right side, but conceptually left is various elements and stuff that is already on the canvas, right is always inspector tools like dev tools in the browser for manipulating things on the canvas.

**Comment by smotched** [comment]
Its when you already have the tree selected, this can solved by instantly hiding left sidebar when dragging starts.

https://user-images.githubusercontent.com/91352309/160056755-88eb4099-ffdd-420f-9f9d-0ad26bad46b7.mov

I see the overlap issue, I like the idea of distinctly separating left and right sidebar but there has to be a better way

not urgent though, just something to brainstorm along the way

**Comment by kof** [comment]
Yeah, if there is a better way I am happy to iterate, Webflow does it this way too right now.

Good catch, it was supposed to close when you start dragging, it's a bug!
