### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by piyusharorawork** [webstudio-is/webstudio-designer#23]
In the style panel , currently the values are selected via menu component . Need to replace menu with the select for better UX experience . 

The Select component should behave similar to menu component with already working features : 
- User should be able to preview on canvas on hover 
- User should be able to preview on selection via keyboard
- User should be cancel the changes with escape button 
- User should see the dropdown when pressing arrow down 

![image](https://user-images.githubusercontent.com/31386968/162564793-fcb442b3-4f0e-4d89-b5fd-7334bfd2f87f.png)

**Comment by kof** [comment]
Current problems with Autocomplete:

- [ ] it should not update the value in the input on hover
- [ ] too much delay between hovered item change and preview on canvas
- [ ] when dropdown is open and user clicks on input - close it
- [ ] if input is not empty - arrow up/down don't open autocomplete, they navigate it
- [ ] there should be no delay when hovering items to highlight the item
- [ ] click outside should close it without actually creating a click on whatever control one clicked outside
- [ ] focus should not open dropdown
