### ISSUE TITLE
Too many display property options in style panel

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#261]
Right now, since we are trying to support all CSS values, the list of display values is just huge, despite that only a few of them will be used 99.9% of the time.

What can we do to make it still support all options and yet make it easy for the user?

<img width="257" alt="Screenshot 2022-09-05 at 20 12 43" src="https://user-images.githubusercontent.com/52824/188499389-2d7bb2a6-340c-43be-9df6-ccd4fac74ba0.png">

**Comment by kof** [comment]
This applies to many other properties as well, so lets figure this out for this one first

**Comment by taylornowotny** [comment]
Isn't that what the properties panel is for? Anything not in the main UI could be added via the props panel. 

If not that, then this is a use-case for custom code snippets.

In the menu pictured I would only show Block, Flex, Inline-Block, Inline, and Grid (when we can support it).

**Comment by kof** [comment]
by properties panel you mean css editor? Props are for component props / attributes

**Comment by kof** [comment]
CSS Editor is one option for sure, but I feel like there are other options, e.g.:  sort by popular properties first, make the list container much smaller to be less overwhelming when opening it, then let user scroll it if needed, they don't have to though because all values they need will be in the first 4-5

**Comment by kof** [comment]
So will will reduce the amount of suggested properties to the subset Webflow also provides for style panel and we will enable all of them in the linked CSS editor

**Comment by TrySound** [comment]
Css has display: ruby?

**Comment by kof** [comment]
> Css has display: ruby?

exactly, among others thing nobody uses

**Comment by kof** [comment]
We still want to enable them all from CSS linked editor, so they will be autocomplete there and we don't want to remove that info from our css-data, but we need separate lists for things we show in the style panel

**Comment by TrySound** [comment]
> [Internal](https://developer.mozilla.org/en-US/docs/Web/CSS/display#internal)
[<display-internal>](https://developer.mozilla.org/en-US/docs/Web/CSS/display-internal)
Some layout models such as table and ruby have a complex internal structure, with several different roles that their children and descendants can fill. This section defines those "internal" display values, which only have meaning within that particular layout mode.

IMO these along with their parent should have separate editor rather than manual css editing

https://developer.mozilla.org/en-US/docs/Web/CSS/display

About "flow" and "ruby" maybe do not include experimental features?

**Comment by kof** [comment]
yeah, we should remove experimental features at the css-data generation step

**Comment by TrySound** [comment]
Looks like radix do not allow shorter scrollable lists by design.

https://github.com/radix-ui/primitives/issues/1193#issuecomment-1050716892

**Comment by kof** [comment]
Why do we need a scrollable list if we have only 6 items?
