### ISSUE TITLE
Better style panel UI discussion

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#27]
Lets make this a place to discuss what we want the style panel UI to have and how it should look

**Comment by taylornowotny** [comment]
https://user-images.githubusercontent.com/86495896/175577750-fa79b485-8991-4fc2-a3dc-ff61b9013f53.mp4

**Comment by kof** [comment]
@taylornowotny @natlusyht @okonet I think we should close this issue and create more specific once where needed

**Comment by kof** [comment]
Closing in favor of separate issues
