### ISSUE TITLE
Reuse code in edge deployments

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio-designer#272]
Currently, shared things are copy-pasted from the designer to the edge deployments. We need to fix this.

A possible solution is to publish the shared parts to an npm package, so they could be reused in several places.

**Comment by andrasbacsai** [comment]
@kof Wdyt?

**Comment by kof** [comment]
Right, we need to figure out how to meaningfully create those packages, so that they make sense for all use cases we have soon, which are
1. apps: designer, dashboard, auth, canvas
2. workers
3. cli

**Comment by kof** [comment]
@andrasbacsai this one can be closed?
