### ISSUE TITLE
Trying to make a part of a Bold text Italic results in duplication of text

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#289]
1. Start editing a Paragraph. For example, it has text "hello world"
2. Make entire text bold "hello world" -> "**hello world**"
3. Try to make the word "world" italic
4. The result is not  "**hello _world_**" but "**hello world**_world_"

**Comment by TrySound** [comment]
How to represent overlap in navigator? If we remove style their whole range is removed. Should we add something like "Italic Bold Text"?

**Comment by rpominov** [comment]
Webflow does something like this:

```
Paragraph
 |- Bold
 |- Bold
     |- Italic
```

We should probably do the same, but "Italic Bold Text" might be also a good option.

/cc @kof

**Comment by kof** [comment]
Aren't we technically nesting bold in italic or italic in bod depending on what was first? If we are nesting them in HTML then we should represent the same structure in navigator I guess?
