### ISSUE TITLE
[design system] Better Icon component

### ISSUE THREAD

**Issue by okonet** [webstudio-is/webstudio-designer#308]
> I added this since it would otherwise collapse the icon as far as I remember. I think the way how icon is made now needs reworking. I'd like Icon to have `size` prop that would define the size internally + currently Icon is not accessible so we probably need add a `label` prop so it can be used by assistive tech. Let's do a follow up for this?

_Originally posted by @okonet in https://github.com/webstudio-is/webstudio-designer/pull/268#discussion_r979914052_

**Comment by TrySound** [comment]
Size is added. For label can be used aria-label. No need in custom prop.
