### ISSUE TITLE
Use sync status indicator for all ongoing requests & show native dialog if user tries to leave the page during sync (beforeunload)

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#367]
We have a sync status indicator for canvas edits sync. We should use it for other requests as well (e.g. saving page settings).

- [ ] Show sync indicator during any Remix form submission.
- [ ] Prevent user from leaving the page when there's unsaved data using native `beforeunload` dialog.
- [ ] Make sure we handle correctly the case when there's unsaved data but the submission haven't started yet because of debounce or some other timeout.

----

 https://github.com/streamich/react-use/blob/master/docs/useBeforeUnload.md

**Comment by kof** [comment]
We have a syncState event with states.

**Comment by kof** [comment]
Created a new issue with a new mindset: assuming you are always online and get rid of that icon. Only show an offline icon when there is a problem with syncing.

https://github.com/webstudio-is/webstudio-designer/issues/863
