### ISSUE TITLE
Improve working locally with separate repository like sdk

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#38]
Working on sdk and designer simultanously currently is a nightmare, in the attempt to try and keep SDK in a separate repository, we still need a way to work with it like its same repository.

Yalk could be the solution here, https://github.com/wclr/yalc let try it out

**Comment by SaraVieira** [comment]
Good and bad news here 

Good news it works, bad news it doesn't care about changes, you have to always "publish" a new version

**Comment by kof** [comment]
Is this autmatable to the level one can work with it like its a monorepo?

**Comment by kof** [comment]
another tool that was mentioned in [this](https://twitter.com/oleg008/status/1510695966680170504) thread is https://www.npmjs.com/package/relative-deps by @mweststrate

**Comment by SaraVieira** [comment]
@kof Nop, so the workflow is following

sdk:
- Make changes
- run yak publish

This means that it only really tracks changes after you build and "publish" your package

**Comment by kof** [comment]
I mean I can run a local watcher and run yalc publish automatically, if that's making things faster depending on the DX we want

**Comment by SaraVieira** [comment]
I'm trying the other one, i don't think yalc is also a great solution because it creates many hidden files

**Comment by kof** [comment]
let me know what you found usable, we need to add some minimal docs for it and start using, because the current situation is terrible

**Comment by SaraVieira** [comment]
This one https://github.com/mweststrate/relative-deps works pretty well for me but the issue is that it hardcodes the path of the SDK package and I need to see what happens when that folder is not there

**Comment by kof** [comment]
hardcoded path is probably the lowest evil if the rest works

**Comment by kof** [comment]
we merged this one
