### ISSUE TITLE
Eslint rule for 2 new cases

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#397]
Let's add an eslint rule for 2 new cases

1. == (only allowed to compare to null)
2. define some min length for variables min length, to avoid using one-char  variables or types like T, I think mostly we just need to check 2+ chars

_Originally posted by @kof in https://github.com/webstudio-is/webstudio-designer/pull/378#discussion_r1014797222_

**Comment by istarkov** [comment]
+ Rule to not use `import React` if jsx only 
and `import * as React` in case of React.useBlabla etc is used.

**Comment by TrySound** [comment]
named imports are fine, just forbid `import React from 'react'` which prevents mangling.
Btw can be done with https://eslint.org/docs/latest/rules/no-restricted-imports

**Comment by andrasbacsai** [comment]
Adding the following rules to `@webstudio-is/eslint-custom-rules`:
```js
{
    eqeqeq: ["error", "always", { null: "ignore" }],
    "id-length": ["error", { min: 2 }],
}
```
And add `plugin:react/jsx-runtime` to extends for React 17+ new JSX transform.
