### ISSUE TITLE
Webstudio UI Design System

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#43]
We need to improve the design system of webstudio UI itself, especially colors we use, but also everything else in the [theme](https://github.com/webstudio-is/webstudio-designer/blob/main/app/shared/design-system/stitches.config.ts#L132) and restyle/finetune all components we use. 

AKA make the designer look and feel great :)

**Comment by taylornowotny** [comment]
I'll be working on this as we develop the UI

This is an area of ongoing development so it'll never be "done". We will be iterating and improving the UI and the design system in parallel.

For starters, here's the color system we are using:
https://www.radix-ui.com/docs/colors/getting-started/installation

**Comment by kof** [comment]
This seems like a useless issue now
