### ISSUE TITLE
Open page settings button should also close settings if they are already opened

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#430]
Currently when you open page setting, the settings button turns into a arrow icon. Clicking the icon doesn't allow user to close the settings, they have to reach to tру close button in the settings panel.

<img width="255" alt="Screenshot 2022-11-09 at 14 21 19" src="https://user-images.githubusercontent.com/825702/200804924-d4494cba-d59e-4ef5-88f9-ec1080fe72a9.png">

- [x] Change the arrow icon into a button that closes the settings
- [x] Use the same idle / hover states as with menu button

**Comment by rpominov** [comment]
@taylornowotny What do you think about this? I and Oleg think it's a good idea, but in design it seem like wasn't supposed to work like this.

**Comment by taylornowotny** [comment]
I agree - good idea

Can you keep the settings button there and just change the icon to the arrow while the page is open?

idle and hover can use the same colors as the settings button normally

I will update the design

**Comment by rpominov** [comment]
Great! Was going to do exactly that.

**Comment by rpominov** [comment]
> In fact in the arrow icon is a small icon button component in the design, same as the settings button.

Not sure I understand this bit, but otherwise everything makes sense, was going to do the same.

**Comment by taylornowotny** [comment]
> > In fact in the arrow icon is a small icon button component in the design, same as the settings button.
> 
> Not sure I understand this bit, but otherwise everything makes sense, was going to do the same.

Icons that are interactive will always be a part of a button component. In this case it is the **small icon button** component.
<img width="287" alt="Screenshot 2022-11-09 at 10 11 01 AM" src="https://user-images.githubusercontent.com/86495896/200908212-80dc173c-3cb8-48f3-a84b-586571406c1d.png">
