### ISSUE TITLE
Pages UX fixes

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#431]
- [x] Add placeholders to fields "/home" for Path, "My awesome site" for Title etc.
- [x] When opening page settings the Name field should gain focus
- [x] When creating a new page, Name should be pre-filled with some value, and text in Name should be selected so it's easy to delete the pre-filled value
- [x] When creating a new page, Path and Title should be generated automatically from Name, unless user have edited them
- [x] The close button tooltip should be aligned normally (centred like other tooltips)
- [x] Better design for the "Create" button
- [x] Better settings panel animation ( #376 )
- [x] Home page should not have a path field

**Comment by rpominov** [comment]
Hey @taylornowotny .  Could you help a bit with this?

> Better design for the "Create" button

<img width="184" alt="Screenshot 2022-11-09 at 14 59 53" src="https://user-images.githubusercontent.com/825702/200812934-b58f249d-43c5-4a65-9ec6-c0934a7f5f9a.png">

Could you make a design for the create button? I think we should put it in the title like Webflow does.

> The close button tooltip should be aligned normally (centred like other tooltips)

Why do we make the close button tooltip aligned like this? Should we make it centred?

<img width="159" alt="Screenshot 2022-11-09 at 15 01 41" src="https://user-images.githubusercontent.com/825702/200813331-17dd68dc-a105-4124-96ff-ccc881d20b12.png">

**Comment by taylornowotny** [comment]
@rpominov Yes I can design a better "create" button but what is this button used for - what is it's context? If this is the button for creating a new page there is already a button for that.
<img width="121" alt="Screenshot 2022-11-09 at 8 35 33 AM" src="https://user-images.githubusercontent.com/86495896/200887593-d55d9966-f567-4f50-84e4-c19cdc39675e.png">

> The close button tooltip should be aligned normally (centred like other tooltips)

Tooltips are positioned so they do not flow outside of their panel. Check the Tooltips page in the design docs - all the info you need is there. 

Do you think it would be preferable to have tooltips centered even if they overflow the panel? I am open to this if there is an advantage to doing it this way

Lastly, the designs for Pages got messed up as part of a layout update so the layout is currently jacked up. It'll be fixed before the end of the day

**Comment by kof** [comment]
> Tooltips are positioned so they do not flow outside of their panel. Check the Tooltips page in the design docs - all the info you need is there.

@taylornowotny where does the idea is coming from that the boundary should be their panel? Everywhere I checked boundary is the viewport, not the box.

**Comment by kof** [comment]
> Do you think it would be preferable to have tooltips centered even if they overflow the panel? I am open to this if there is an advantage to doing it this way

It looked a little weird to me that the tooltip looks the way it looks right now in figma and in implementation, then I went checking in Figma UI and some other places, and tooltips never do that thing unless they have to because its the end of the window.

I think you want them visually centered as long as you can, feels weird otherwise

**Comment by rpominov** [comment]
> do we anticipate that page creation could be slow?

Can be slow if user's internet is bad

**Comment by rpominov** [comment]
Checked WF, btw: with a slow connection, you click on "create" and nothing happens for some time as if it didn't register the click.

**Comment by taylornowotny** [comment]
understood, will add that state to the button

**Comment by kof** [comment]
@rpominov aren't you optimistically creating?

**Comment by rpominov** [comment]
Multiple reasons to not create optimistically:

1. We're navigating the canvas to the new page, and the way it currently loads data the page has to exist in DB by that time
2. If there're validation errors but we've already closed the panel, we won't be able to show them near the fields
3. If creation fails, the UI transition back to the state where the page doesn't exist will be very confusing

I don't think it's a good idea

**Comment by kof** [comment]
Got it, then lets make sure while its creating we show a "wait" cursor (may need a new state to the button) and that state should make the button disabled for the time being so that user can't click it twice

**Comment by kof** [comment]
@rpominov please don't forget to use reduced motion

**Comment by taylornowotny** [comment]
<img width="874" alt="Screenshot 2022-11-09 at 5 27 53 PM" src="https://user-images.githubusercontent.com/86495896/200980767-254250ca-23b1-4af0-a2c2-d09bacc81026.png">

I updated everything on the Pages panel in figma, including the new button and new tooltip positioning.

The panels are now using our new sizing and spacing system. DM me @rpominov or talk with Oleg if you need help understanding this new system. I will make a video explanation when I have the whole design updated but I'm still working on that.

**Comment by rpominov** [comment]
@kof Should we add the save changes button, rather than saving automatically? I'm for it, will simplify some things.

**Comment by kof** [comment]
@rpominov do you mean a "pending" state on the design system button component?

**Comment by rpominov** [comment]
We've discussed in chat with @kof regarding the "save changes" button for the case when you edit an existing page. Oleg thinks we should **not** add it: save changes automatically as it works now.

I don't completely agree, because we're erasing old values when we save the new. For me personally it feels better when I decide when to save, and may decide not to save at all. Not sure how it feels for majority of users though.

@taylornowotny what do you think?

**Comment by kof** [comment]
@taylornowotny and @rpominov I would love us to come up with foundational principles on "when" to use a safe button vs when to safe automatically. My idea is that everything should feel instant and only in rare occasions we add a button, like in case of a "create" action or "delete" action.

**Comment by kof** [comment]
Another way to think about it with buttons: "is the change hard to undo for the user?" In case of forms, user can always go into a field and hit undo/redo shortcuts. They are natively supported in every form.

One thing to also note here is that as long as the user didn't publish, the changes aren't live. So anything they do they can undo without making it visible to their users.

**Comment by taylornowotny** [comment]
I was thinking the same as @rpominov that it's good to have a save button here because data could be lost.

I also understand where you are coming from @kof regarding using save buttons minimally

What are the implications of this decision on collaboration?

Although I am inclined to want a save button here, I can't actually think of any situations where that would help me. I am fine with either way on this
