### ISSUE TITLE
Outline is not always updating the size or position

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#433]
When changing margin or font size for example, outline doesn't update. When changing width/height - it does.

**Comment by kof** [comment]
seems like it was only broken in a branch, not on main

**Comment by rpominov** [comment]
Steps to reproduc:

1. Add a Heading
2. Set its `Display` to `inline`
3. Try to change its `Font Size`
4. Outline doesn't change even though the size have changed due to `Font Size`

**Comment by rpominov** [comment]
ResizeObserver doesn't work for inline elements: https://github.com/WICG/resize-observer/issues/19#issuecomment-246749511 , https://github.com/w3c/csswg-drafts/issues/4507

**Comment by rpominov** [comment]
The only solution that comes to mind is to do polling if the element is `inline`. Surprisingly little information about this issue on the internet, didn't find any other solutions.

**Comment by kof** [comment]
Or in case of inline to getBoundingClientRect every time any style of that element changes, then compare if it has actually impacted the metrics.

**Comment by rpominov** [comment]
> every time any style of that element changes

There's no event we can use for that in general AFAIK. Might be possible for the own style of the element, but for the inherited styles probably no way.
