### ISSUE TITLE
Changing media queries seems to be breaking outline

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#446]
Try to switch between mobile and tablet breakpoint for example, it leaves the outline stuck in the previous position. See both switching media queries from the list as well as from the slider resizing the width

**Comment by TrySound** [comment]
Cannot reproduce on main. Outline updates. Not smoothly though

**Comment by kof** [comment]
Seems like its only reproducible with inline elements, I remember Roman fixed a related bug already once in useMeasureInstance

https://user-images.githubusercontent.com/52824/205516395-78d45c87-8706-4597-808d-0f8be0c3ba3f.mp4

**Comment by rpominov** [comment]
Probably need to add an event that corresponds to breakpoints change here: https://github.com/webstudio-is/webstudio-designer/blob/fb946ab2966dfeb3ee84c2fcbd52e43f5dbfaa9b/apps/designer/app/canvas/shared/use-measure-instance.ts#L12-L18
