### ISSUE TITLE
Prevent merging PR's that fail checks

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#45]
We have `yarn checks` command that runs static checks and unit tests and we shouldn't be merging PRs when it exits with 1

**Comment by SaraVieira** [comment]
So we need GitHub actions? 

I can add that but we currently have typescript issues

**Comment by kof** [comment]
`yarn checks` passes on my machine, must be something setup specific

**Comment by kof** [comment]
`yarn checks` passes on my machine, must be something setup specific

**Comment by SaraVieira** [comment]
it was my branch! Closing this because this was added with https://github.com/webstudio-is/webstudio-designer/pull/48

**Comment by SaraVieira** [comment]
Hm? It didn't delete automatically, i deleted it
