### ISSUE TITLE
Reuse code for Edge version (pages)

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio-designer#451]
We want to reuse most of the code from the designer in our edge version.

## The problem
Because most of the functions, like database access, are not separated logically. The edge version is not connected to our database, so I cannot reuse it 1:1.

## Example 
For example, I would like to reuse [this](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/app/routes/%24.tsx).

## Best solution
We need to come up with a solution where it would be easy to reuse (and later on test) most - or not all - parts from the designer repository in the edge repository.

**Comment by andrasbacsai** [comment]
@rpominov Can you please help me with this topic?
/cc @kof

**Comment by rpominov** [comment]
I think we already share most of what can be shared. 

From `$.tsx`: 
 - only `meta()` can be shared, 
 - `loader` will be different in worker, 
 -  and from `Content` the sharable part is just this line: `<InstanceRoot data={data} />`.

**Comment by kof** [comment]
As long as we can make sure our CI fails when we do breaking changes, we can do "some" copy paste that is not 100% reuse.

My biggest worry is this:
1. someone changes designer, tests designer
2. we merge the change
3. workers in production break: no obvious reason what caused it, not being able to catch it before it happens on CI.

As long as we prevent this disaster from happening I am good.

**Comment by rpominov** [comment]
For making sure this doesn't happen I think it's more important that:
1. there's a way to run the worker locally so we could test, 
2. and more people work on the worker. If I'm making a change that affects worker, it should be my responsibility to also update worker. And code sharing will come naturally from that.

Maybe we use it already, but Cloudflare has a tool to run workers locally

**Comment by kof** [comment]
> more people work on the worker. If I'm making a change that affects worker, it should be my responsibility to also update the worker. Code sharing will come naturally from that, btw.

The hard part is knowing what you need to test. It's not going to be obvious unless we make something fail.

**Comment by rpominov** [comment]
> The hard part is knowing what you need to test. It's not going to be obvious unless we make something fail.

We will know what to test if we all work on the worker and know how it works etc.

**Comment by kof** [comment]
> We will know what to test if we all work on the worker and know how it works etc.

true, right now only @andrasbacsai knows, but we should get into it too, right now @andrasbacsai should decide how we make sure workers don't break

**Comment by andrasbacsai** [comment]
1. Workers are working locally. I fix a local KV store issue yesterday, and now all components works with a locally running designer.
2. Tests are hard and as Oleg said, the hardest part is to figure out what to test.

**Comment by kof** [comment]
@andrasbacsai regarding what to test: should we figure out a few basic scenarios? 
if you had to define them, what would they be?

**Comment by rpominov** [comment]
Ah, I meant just testing manually at least. Like you testing everything potentially affected as part of developing a new feature. Automated tests would be great too ofc. if possible 😄
