### ISSUE TITLE
Performance issues in the designer app

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#452]
Our `apps/designer` app seem to take `100-200ms` to produce any response locally

<img width="1151" alt="Screenshot 2022-11-15 at 18 20 22" src="https://user-images.githubusercontent.com/825702/201942647-1ce21436-5250-4e30-8746-4dc7d3d334eb.png">

**Comment by rpominov** [comment]
We should consider setting up some regression tests for performance

**Comment by rpominov** [comment]
This is because remix re-import entire app code on every request in dev mode: https://github.com/remix-run/remix/blob/41f921b33feff976b54b5fe92d34618a45fe7a04/packages/remix-serve/index.ts#L32

I've put `console.time / timeEnd` around this `require` and it takes ~100ms consistently for me locally.

**Comment by rpominov** [comment]
In prod mode locally request to `/dashboard` takes 10-20ms for me. Was testing everything on `/dashboard`, btw.

**Comment by rpominov** [comment]
So, I think everything is as expected in dev mode

**Comment by kof** [comment]
Is dev mode taking for you also 100-200ms?
