### ISSUE TITLE
Option names and select value do not match for the Box tag property at the properties panel. 

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-designer#465]
Option names and select value do not match for the Box tag property at the properties panel. 
_uppercase first letter_

https://user-images.githubusercontent.com/5077042/202745991-0a61b978-1a47-4e1f-b2d9-05ee8d2f9bba.mov

**Comment by istarkov** [comment]
We have same behaviour for style `Display` 
flex/etc
<img width="230" alt="image" src="https://user-images.githubusercontent.com/5077042/207275583-fd82aee2-a050-4834-82bf-6117808b4e15.png">

<img width="176" alt="image" src="https://user-images.githubusercontent.com/5077042/207275720-d6745b5b-362c-423c-926c-fe4526fbb9dc.png">

**Comment by kof** [comment]
cc @taylornowotny

**Comment by istarkov** [comment]
From discussion:

@taylornowotny wrote:

My suggestion is this:
- Show an intuitive name in sentence case for property labels. The name should be as close to CSS as reasonable, but may be a different name and will not have hyphens.
- Show the CSS names in tooltips for properties and values, with correct syntax
- Use CSS names for values as much as possible, in sentence case with or without hyphens 

Why use sentence case? Capitalized first letters will be consistent with the rest of the UI and consistent with other UIs. We are going along with the user's expectations based on their past experience with other similar programs. Users can look up documentation all the same whether the first letter is capitalized or not. If we use correct CSS syntax outside of the context of a code window it look pretty weird to me. I realize that's not very objective, but in this case I believe my perspective is representative of our core user, a designer with limited code experience.

**Comment by kof** [comment]
@istarkov we discussed this with @taylornowotny, the most correct notation is "Inline Flex" both words capitalized
