### ISSUE TITLE
Eslint rule for index modules

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#482]
It should prevent importing specific modules from a folder that has an index module. Index is like a public interface. If any export is not exported from index - it's private.

This way we can export things from modules that are for reuse between other modules from the same folder but NOT as a public interface. Basically This is how we can have private modules.

**Comment by kof** [comment]
Part of https://github.com/sindresorhus/eslint-plugin-unicorn/

**Comment by andrasbacsai** [comment]
Do you mean for example to:
- prevent `import { prisma } from "@webstudio-is/prisma-client"` 
- allow `import { prisma } from "@webstudio-is/prisma-client/src/prisma"`?

**Comment by kof** [comment]
When a folder has an index module, imports should never reach into the folder by using path, they are only allowed to import what's exported from that index. Index module is the public interface of that folder.

**Comment by andrasbacsai** [comment]
I used `import/no-internal-modules` that prevents importing modules from sub-folders but only allows from index files. If this is not suitable, I think we need to write a custom eslint rule.

**Comment by kof** [comment]
Is this allowing to use internal modules when no index.ts provided? otherwise sounds like what we need

**Comment by andrasbacsai** [comment]
Unfortunately, not. We need to allow those internal modules.
