### ISSUE TITLE
Can't edit Link's text

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#487]
1. Add a Link component
2. Double-click to start editing the text
3. Delete all text
4. Start entering new text

After you enter the first letter, it doesn't allow you to enter the rest

**Comment by TrySound** [comment]
Maybe we need to distinct block link and inline link?

**Comment by TrySound** [comment]
Space cannot be entered inside button because of default behaviour

**Comment by TrySound** [comment]
Form button is edited with separate panel, without inline editor

**Comment by rpominov** [comment]
> Maybe we need to distinct block link and inline link?
 
Sounds like a good idea, especially because afaik it's the only component that can be inline, but has `isInlineOnly: false`. If there won't be any such components, it can simplify code in some places.

**Comment by TrySound** [comment]
> Another case is when cursor before or after text, input does not work for some reason

Yep, this case is fixed when I add display: block. inline-block doesn't work either.

**Comment by TrySound** [comment]
display: table works and preserves inline style!

**Comment by TrySound** [comment]
Funny thing, this is not lexical but contenteditable behaviour
https://codesandbox.io/s/shy-cookies-0sx1qe?file=/src/index.js

**Comment by kof** [comment]
Webflow works with a link and display inline

**Comment by TrySound** [comment]
Maybe we don't need Link component at all. It's same text block with link but introduce bugs like this and breaks links inside text block when double click on them.

**Comment by kof** [comment]
We are going to use a Link component from Remix that comes from the router for example. User may have other needs as well in a custom sdk

**Comment by TrySound** [comment]
This is fine. I mean do we need a separate Link element in left panel if text with link is the same?
