### ISSUE TITLE
Unable to delete input element

### ISSUE THREAD

**Issue by piyusharorawork** [webstudio-is/webstudio-designer#5]
So I tried to place 2 elements , button and input . Now deleing the button was easy by just selecting the button and hit delete . 

But for input element , it is basically deleting the text inside the input element but not the input element itself. 

So we need to somehow figure out are we deleting the contents of input or the input itself . 

( PS . I tested this on the brave browser in m1 mac air if it is relevant)

**Comment by kof** [comment]
It's a bug, designer is supposed to prevent entering text inside the input

**Comment by kof** [comment]
fixed, deploying, let me know if you still see that problem!

**Comment by kof** [comment]
Just tested again and it's not fixed, I am surprised I have seen it working yesterday

**Comment by kof** [comment]
Ok, now seems to be fixed

**Comment by piyusharorawork** [comment]
@kof Yes it fixes the issue . But now the only way I was able to add text / placeholder to the input element is by going to the properties and setting value = "SOME TEXT" . Is it expected or is there a better way for this

**Comment by kof** [comment]
Input value is what user would be entering, right? As a designer, why would
you want to set the value?

Placeholder - yes its the prop. We need a way to show available props though
