### ISSUE TITLE
Make it harder to break the worker

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#513]
We need to avoid two situations:

 1. Developer works on a feature and finishes it without realising the worker is broken now (will not work properly with the new code in designer)
 2. Designer app deployed in prod is incompatible with the worker deployed to prod
 
What can we do? Suggestions from me:

- Re-use as much code as possible so when we test designer app we also test most of the code in worker (I think we're good on this already, just need to keep it up)
- Make it easy to run worker locally, so developers would test locally while working on features (maybe this is already done).
- Setup auto-deploy of the `main` branch of the worker, so we know our designer app preview deployments point to the latest version of the worker and we can test that combination in preview.
- Figure out a workflow for when you need to change the worker as part of implementing a feature. This is not trivial because worker is in a separate repo, and because we don't have preview deployments for worker. So we cant test feature in preview when you need to change the worker.
- Automate worker deployment to prod on commit to the `prod` branch, so the deployment to prod is still just a PR merge.

@andrasbacsai What do you think? What can we do out of what I suggested or in general to solve `#1` and `#2`? For now it's a research issue, but we need to have a plan and make it actionable.

@istarkov You have a lot of experience with this stuff, maybe you have some ideas?

**Comment by andrasbacsai** [comment]
>Re-use as much code as possible so when we test designer app we also test most of the code in worker (I think we're good on this already, just need to keep it up)

We are already doing it, as you said. Unfortunately, some parts cannot be shared (like how we access data, obviously, SQL vs KV store), so yeah, we just need to keep it up.

> Make it easy to run worker locally, so developers would test locally while working on features (maybe this is already done).

A few weeks ago, I made a few modifications to the SaaS repository, so we can test all workers locally, with a local KV store.

>Setup auto-deploy of the main branch of the worker, so we know our designer app preview deployments point to the latest version of the worker and we can test that combination in preview.

We could set up a flow, that `main` branch will be deployed to staging and `prod` to prod. Staging workers are connected to `Preview Deployments` (docs will be in the saas repo soon), so we can test everything.

**Comment by rpominov** [comment]
> A few weeks ago, I made a few modifications to the SaaS repository, so we can test all workers locally, with a local KV store.

Great, I'll test it.

> We could set up a flow, that main branch will be deployed to staging and prod to prod.

Ok. This sounds like an actionable TODO item then.

> Figure out a workflow for when you need to change the worker as part of implementing a feature. This is not trivial because worker is in a separate repo, and because we don't have preview deployments for worker. So we cant test feature in preview when you need to change the worker.

Any ideas on this? Maybe it's possible to deploy every branch of `webstudio-saas`? Although we'd also need to be able to point the designer preview deployment to this separate deployment of worker. Maybe if two branches have the same name we could link deployments automatically somehow?

**Comment by rpominov** [comment]
> Great, I'll test it.

I've stuck at this error

![image](https://user-images.githubusercontent.com/825702/204248088-b82a77b1-34fc-4068-ac82-0c79be987079.png)

**Comment by kof** [comment]
we had this already fixed in once @istarkov ?

**Comment by istarkov** [comment]
Yes, rebase

**Comment by rpominov** [comment]
> We could set up a flow, that main branch will be deployed to staging and prod to prod.

There's a complication:

1. We share code via NPM packages
2. If we just re-deploy worker when it's repository changes, this will nor be enough
3. We also need to re-deploy when code that we share via packages changes

Here's a case where we've hit this problem https://github.com/webstudio-is/webstudio-designer/issues/581#issuecomment-1346335985

Maybe we should reconsider sharing via NPM packages after all...

**Comment by kof** [comment]
@andrasbacsai can this be closed?
