### ISSUE TITLE
Typescript types like UnionToIntersection, UnionToTuple

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-designer#544]
https://github.com/webstudio-is/webstudio-designer/blob/07d2bf836c832b23e6b9732b38238a11bd751ce6/apps/designer/app/designer/shared/design-tokens-manager/schema.ts#L4-L14

Move in types.d.ts or like, document and share.

Docs:
`UnionToIntersection` - uses [Distributive Conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) to get union of functions i.e.
A | B | C transforms into (A)=>never |  (B)=>never | (C) => never
When inferring type `I` such as each union member above, extends (I)=>never.
That caused _(contravariance)_ `I` must extend A B and C. Obviously such type is `A & B & C`

`UnionToTuple` - uses that ReturnType of intersection type is the return type of the last member of intersection i.e.
`type X = ReturnType<(()=>number) & (()=>string)>`  infer `X` as string
Its documented behavior [here](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types) 
> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by kof** [comment]
This type of issue should be referenced next to the todo in code, because I am right now moving the code, so it may be harder to find

**Comment by kof** [comment]
we already removed them
