### ISSUE TITLE
Update pop-up text menu

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#555]
We are using new docs!

Here's a link to the page about this feature. Please read the whole thing before beginning to implement.
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/Design-Docs?node-id=1%3A4&t=BoiiM5PaUoKXooe5-1

Notice that this component uses icon buttons, not a toggle group.

**Comment by kof** [comment]
This is done, right?
