### ISSUE TITLE
Flex grid control is not showing correct states

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#590]
We need to retest every state and fix the representation in the grid control according to the design

https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=8%3A1861&t=e1fHzKZPDyeTnP7L-4

**Comment by TrySound** [comment]
By grid you mean flex, right?

**Comment by TrySound** [comment]
What's "stretch, A"?
<img width="221" alt="image" src="https://user-images.githubusercontent.com/5635476/209216844-54c15613-cf9f-4009-9170-c613ff3c566c.png">

**Comment by TrySound** [comment]
Btw align-items default "normal" behaves like stretch
<img width="76" alt="image" src="https://user-images.githubusercontent.com/5635476/209222092-bdff3912-be7e-4a99-9dc9-31283567c0df.png">

**Comment by TrySound** [comment]
Here's how `align-items: baseline` looks like
<img width="92" alt="image" src="https://user-images.githubusercontent.com/5635476/209224125-f2030a2d-7081-4b4d-9a46-47763342a634.png">

**Comment by TrySound** [comment]
stretch, A probably meant space-between. Though from css point of view it shows space-around
<img width="157" alt="image" src="https://user-images.githubusercontent.com/5635476/209225273-dbc4d824-c3ba-4848-895c-026b55a8476b.png">

While space-around doesn't behave this way and may be misleading
<img width="160" alt="image" src="https://user-images.githubusercontent.com/5635476/209225376-39bfc9ce-b94f-494f-9ce4-e65f3c7503f8.png">


Here's how space-between actually looks like
<img width="86" alt="image" src="https://user-images.githubusercontent.com/5635476/209225458-b9f57856-7bf9-4b7e-bb1a-0b42cb449f3f.png">

**Comment by kof** [comment]
> By grid you mean flex, right?

Grid control is the box with 9 dots, a little confusing name since flex/grid css
