### ISSUE TITLE
When I click reset, the control for that value quickly jumps right before rendering the new value

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#600]
- [ ] Found a visual bug - when I click reset, the control for that value quickly jumps right before rendering the new value

https://user-images.githubusercontent.com/52824/207019134-486d5fee-2453-4810-b746-5526b00e74d2.mp4

_Originally posted by @kof in https://github.com/webstudio-is/webstudio-designer/issues/583#issuecomment-1346213429_

**Comment by TrySound** [comment]
All reset issues comes from the fact we compute values from dom instead of data which is much faster and bullet proof

**Comment by kof** [comment]
One place where we can't compute from data with full certainty is when we don't have a value set in our data. We kinda need to know what browser value is.
