### ISSUE TITLE
Smallest breakpoint should start from 0

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#621]
I used the lower bound of the breakpoint (min-width) as a way to set the initial canvas size. But that is a problem if someone resizes the screen on a published site below the smallest media query and looses all styling.

I think the smallest media query should start from 0, but the initial canvas size needs a different logic for decididing what size to start from.

E.g. it could start somewhere in the middle between the smallest media query and the next media query.

E.g. if the smallest one has min-width: 0px and the next one has min-width 768px, we could start at 384 which is in the middle between the two
Another option is to start at the upper bound of the first non-0 media query but before the next one, e.g. if the second mq is min-width 768, then we use 767px to stay on the previous media query at it's max size

**Comment by taylornowotny** [comment]
The only thing I'm sure of is that default canvas size should be at the **lowest** width of the breakpoint.

Scenario: User switches to tablet breakpoint. The canvas is at the halfway size of the breakpoint. User adjusts the sizes of their elements to fit the canvas. Then if the screen width is reduced within that same breakpoint, those sizes may be too large and break the layout.

There is no negative consequence if the screen gets wider, but if it gets narrower than the developer is expecting, then it can cause unintended layout issues. This is is a problem that I have encountered many times in Webflow and it's why I always make sure I'm working on the smallest size of each breakpoint.

Also, it doesn't make sense from the user's perspective to have a breakpoint that goes to 0. There are no screens with a width of 0. If someone can break a layout by narrowing their browser window to an unreasonable size, then that's ok. No problem with that. I think our minimum size should be somewhere around 360 or 420px, but customizable of course.

**Comment by kof** [comment]
The problem I have seen is that our lowest default mq starts at 360 and I managed to resize the browser under 360 and get the fully unstyled site, which should be not possible. I literally lost everything: colors, fonts etc. 

If developer doesn't optimize for under 360 - its fine, but at least the styles for 360 should apple to everything below

**Comment by taylornowotny** [comment]
Yea totally. But it should not be possible to reduce the size of the smallest breakpoint beyond ~360 or so. If users want to design for smaller sizes they can customize their breakpoints.

**Comment by kof** [comment]
>  to reduce the size of the smallest breakpoint

Do you mean it should not be possible to resize the breakpoint beyond 360 or reduce the size the canvas beyond 360?

**Comment by taylornowotny** [comment]
It should not be possible to reduce the canvas below the minimum size & the
default min size should be ~360

It should be possible to customize the min and max sizes for all
breakpoints and also add breakpoints (ideally)

**Comment by kof** [comment]
So one thing that I think is being confused here is resizing canvas vs. actual media queries. While it can be possible to resize canvas to very small size, its not practical to target with a media query that small size specifically, but we use min-width media queries so the query that starts with min-width 0 targets all sizes, I just made it possible because even in the recent demo I managed to record a screen on a smaller than 360 width which had 0 styles applied, while it fixes a niche use case, it doesn't do any harm, please check the pr and see if you see a problem 

https://github.com/webstudio-is/webstudio-designer/pull/639

**Comment by taylornowotny** [comment]
Yes there is a problem. The canvas is the widest size of the breakpoint by default. It should be the opposite. I thought that was very clear from this discussion.

While the smallest breakpoint should go to 0 as you described, there should be a minimum canvas size. I suggest that we show a minimum size for the smallest breakpoint (360 by default) but that is actually the min width of the canvas, not the media query. This seems to be what Webflow does.
eg. When a user opens the smallest default breakpoint the canvas should be 360px width and the breakpoint should say it has a min width of 360, even though it is actually 0.

**Comment by taylornowotny** [comment]
> default canvas size should be at the lowest width of the breakpoint.
