### ISSUE TITLE
Scrub can stuck when moved over right edge of browser window

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#626]
1. Scrub any CSS input (e.g. width)
2. Move cursor all the way to the left border of the browser window
3. Move slowly over the border
4. Cursor gets stuck at the border and you can no longer move it

https://github.com/webstudio-is/webstudio-designer/blob/984e8902ac3a8d708071af57c519aad0e90611af/packages/design-system/src/components/primitives/numeric-gesture-control.ts#L125

The if condition fails when `offset` is `0`

**Comment by kof** [comment]
Yep, saw this too, but couldn't understand when exactly is this happening, because it wasn't reproducible next time I tried
