### ISSUE TITLE
Can't change width of a copied box

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#631]
1. Add a Box
2. Select the Box and copy it (cmd+c)
3. Select Body
4. Paste (cmd+v)
5. Select the copy you've just pasted
6. Try to change its width
7. Observe that even though the number in input changes the actual width of the Box on canvas stays the same

https://user-images.githubusercontent.com/825702/207803118-5b6fedd8-ded4-4a03-97b9-d4d6cff6710a.mov

**Comment by kof** [comment]
I debugged it and turned out this is what's causing it, its a functionality @TrySound added for reset  in useCssRules. I will pass it over to @TrySound because I am not sure why it does what it does

```
      // delete previously rendered properties when reset
      for (const property of rule.styleMap.keys()) {
        if (dynamicStyle[property] === undefined) {
          rule.styleMap.delete(property);
        }
      }
      ```

**Comment by TrySound** [comment]
I get two css rules on the same instance. And looks like one replaces the other. How could this happen?
<img width="599" alt="image" src="https://user-images.githubusercontent.com/5635476/209158894-5487d263-3c5a-4703-b92d-7e9b1408111d.png">

**Comment by TrySound** [comment]
So the issue is here. New css rule is added even though css rule with the same breakpoint could already exist.
https://github.com/webstudio-is/webstudio-designer/blob/main/packages/project/src/shared/tree-utils/populate.ts#L20

**Comment by kof** [comment]
ohh, maybe we should not be populating an instance that is a clone, its already populated, at least `populateInstance ` was initially thought to be used to populate new instances

**Comment by kof** [comment]
I think are calling into createInstance when pasting, though we should be calling into a different function that is aware of the fact that the instance is not entirely new

**Comment by kof** [comment]
"insertInstance" event calls populateInstance

**Comment by kof** [comment]
One option is to rename insertInstance event to insertNewInstance and create insertClonedInstance event for pasting

**Comment by kof** [comment]
Another option is to add anonther flag to "insertInstance" event, e.g. `isPopulated=true` and when this is true, don't call populateInstance() there

**Comment by kof** [comment]
ok Fixing it now
