### ISSUE TITLE
Scrub doesn't work after you type something in the field

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#634]
1. Click on a css input and edit text
2. Try to scrub
3. The scrub does't work

https://user-images.githubusercontent.com/825702/207845576-d9f2a138-eb1e-4dcb-b4e3-06e977fe014c.mov

**Comment by kof** [comment]
I bet its because when you start typing, its in the intermediate state until you hit enter or unfocus, but scrub  needs to work anyways, though it won't because it needs value to be of type unit

cc @istarkov

**Comment by istarkov** [comment]
I especially decided to not add that logic after any edit because was a rule to not propagate any updates if the user started to edit a field until blur or enter.

**Comment by kof** [comment]
Not propagating updates is correct, but the scrub is still supposed to work, because its not going to be logical that suddenly scrub doesn't work any more.

**Comment by kof** [comment]
Hmm, maybe its ok as-is, user is in a typing mode so to say? @taylornowotny

**Comment by taylornowotny** [comment]
Just tested it out. Scrub still works if user presses ENTER or clicks outside of the input after typing. The only time it doesn't work is immediately after typing, with the input still active.

This is totally fine IMO. Not a problem. If we want to fix it for consistency's sake we could do that any time but I don't think this will be a point of frustration for anyone
