### ISSUE TITLE
Review the decision on how to show computed style values in style panel

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-designer#649]
Currently, we show computed values for elements. 
For example instead of `width: auto` we show width px size.
<img width="225" alt="image" src="https://user-images.githubusercontent.com/5077042/208242946-4e714d45-fe00-49d4-bdb6-25927e917337.png">

This is confusing, for example, "Webflow" shows "Auto" with "placeholder color" in case of `width` is not set. Same for other props.
<img width="240" alt="image" src="https://user-images.githubusercontent.com/5077042/208243003-ab1f76be-78ae-4805-ab05-c8eb7de6c14f.png">

If I change the "width" property even on the same (default) value, I see its value with the ordinary `input color` simultaneously with the label background color. _(see width input font color)_

<img width="246" alt="image" src="https://user-images.githubusercontent.com/5077042/208243035-1f80fc45-fc86-4f3d-a188-5be6bc5fe637.png">

In case I need `scrub` in Webflow I click the `alt` button and scrub works with the "computed value".

I think we also need to show "real" values instead of computed ones, and use placeholders (colors) for undefined values (as IMO only color label selection is not enough _I don't have in my mind that label color somehow affects input behavior_)

**Comment by kof** [comment]
@taylornowotny I had an idea to show a computed value when option/alt is pressed and mouse is over the input and otherwise show the value that we have saved, not the computed one

**Comment by taylornowotny** [comment]
If a value is "auto" then why would a user need to know the computed value? Surely that value will be different on different screens, so how would the computed value be useful?

**Comment by kof** [comment]
There are countless situations when you debug a problem, where you need to understand what the actual value is that CSS engine has computed. This is the only way to get to the truth of the problem. It the source of truth.

**Comment by kof** [comment]
When you scrub, even when the value was auto before, you also start from a current computed value

**Comment by kof** [comment]
We could also think of a debug panel that would show all actual values and more

**Comment by taylornowotny** [comment]
Ok just asking becuase I have never been in that situation personally

I agree with 

> I think we also need to show "real" values instead of computed ones, and use placeholders (colors) for undefined values 

Except placeholder is not used for undefined values. It is used for default values, ie. values that have not been applied by the user. For example, a div with no width or height applied has a width and height of auto naturally. This is represented by placeholder text. If a user sets the width to Auto deliberately, then it is no longer placeholder text. The difference in the input + the color of the label tells you that there is a width of auto applied to the element. 

This behavior is described in the docs for our input component. Default values are placeholder color and user set values are darker.
<img width="290" alt="Screenshot 2022-12-17 at 7 28 50 AM" src="https://user-images.githubusercontent.com/86495896/208249262-132c4106-6c25-48a0-8dad-a12612ed09ba.png">

**Comment by kof** [comment]
Btw webflow the inherited or cascaded value as an actual value and only uses "Auto" or "Normal" placeholder  when there is no value known to webflow at all.

I would expect it to not show the value correctly though when the value comes from an external source (e.g. script or stylesheet not controlled by webflow)
