### ISSUE TITLE
Make findInstanceById fast for large trees

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#651]
To make findInstanceById fast, we need a flat map {instanceId: instance}.
We have 2 options: either index the tree on the client and server or make the tree flat: [{id, component, children: ['id1', 'id2'] ...}]
Making it flat will probably make it easier to work with the tree, since we don't need to react to every update of the tree and update the index.

**Comment by kof** [comment]
Btw this change would make immer patches in case of parenting automatically small, so there is no value of an instance with children containing complete instances, resulting in a potentially large tree inside the patch.

**Comment by kof** [comment]
Also if we make the structure look like this: `[{id, component, children: ['id1', 'id2'] ...}]` we still need an index and updating it on each deletion and creation of an instance, if we make the structure look like this: `{instanceId: instance}` then we don't have to maintain an index at all.

**Comment by TrySound** [comment]
We have 3 variants of normalized tree

An object
```
{
  [instanceId]: Instance
}
```

Pros
- straight forward and fast loopup

Cons
- order is not guaranteed so need to store root id somewhere

Array

```
Instance[]
```

Pros
- order is preserved so we can consider first element as root

Cons

- .find by instance id can be slow

Map

```
Map<instanceId, Instance>
```

Pros
- fast lookup
- order is guaranteed so we can consider first element as root

Cons

- stored as array in db so requires conversion on client
- root should be additionally extracted from original array

**Comment by istarkov** [comment]
I'm for Array.
We can always use `map` or `lazyMap` to reference array instances by id. 
Array with some restrictions can be used for collaborative editing  https://blog.excalidraw.com/building-excalidraw-p2p-collaboration-feature/ what is much more simple vs any crdt implementations.


Having in mind collaboration we can never delete items from the local array and because of that supporting `map` or `lazyMap` for array access is easy too. We don't need to manage deletes, so once instance is referenced through a map it can be where forever. 

Arrays also more easy types in DB, to do migrations etc. They can be even put in tables.

**Comment by TrySound** [comment]
Marking items as deleted would give us additional flexibility with arrays. Instead of storing list of ids in instance.children we could store list of indexes. This way arrays lookup becomes very fast and we do not need to convert it to map and have an access to root as first element.

**Comment by TrySound** [comment]
To avoid cleanup necessity and prevent document bloating we can just set null or undefined instead of marking as null.

**Comment by kof** [comment]
The I wonder also what happens performance-wise if we have a 5mb of objects in a plain object datastructure {instanceId: instance}. It may become slow and the cost may become higher in the end than the cost of initializing a Map().

**Comment by kof** [comment]
Marking items as deleted is indeed very interesting for collaboration, because it allows us to undo deletion while the deleted item can be updated by another user while its being deleted 😅

Case:
user1: delete instance 1
user2: same time change instance 1
user1: received the change after its been deleted
user1: undo deletion

Now if we had deleted the item, we would have discarded an updated to it and once we undo the deletion, it would be put back without the update.

With marking as deleted we restore and item that also has received all updates.

**Comment by TrySound** [comment]
It's not necessary to have actual instance. `undefined` will still work if we keep a few last patches and original state. Logux works this way, a few logs/actions are stored as ordered queue and any changes from users are appeared in the right order. So `undefined` will actually will be in patch for a while, not in state.

**Comment by kof** [comment]
I think we can't really rely on the index to identify the instance, because instances can be added at a different order in different clients.

**Comment by TrySound** [comment]
Alright, then we can go with Map but will store as array of [id, Instance] for fast conversion

**Comment by kof** [comment]
Just checked a bit naively, but seems like creating a map using  `new Map([[key, value]])` format is 2x faster than populating a map using a for loop

**Comment by kof** [comment]
Additional question with Map is how fast it is with immer: https://immerjs.github.io/immer/map-set/

**Comment by kof** [comment]
Here is how we can use Map and convert back and forth while keeping a key-value based object format:

```
// From object to Map
const entries = Object.entries({id: instance})
const map = new Map(entries)

// From Map to object
const object = Object.fromEntries(map.entries()) // {id: instance}
```

**Comment by kof** [comment]
The problem with `[[id, instance]]` format is that you can create a Map from it but you can't get it back, because map.entries() returns a MapIterator, not an array and I don't see how we can serialize it without writing a for loop ourselves, which I assume will be slower than `Object.fromEntries`

**Comment by TrySound** [comment]
```
Array.from(new Map([[1, 2], [3, 4]]))
```

**Comment by kof** [comment]
Good one, lets measure perf differences using esbench

**Comment by kof** [comment]
Benefit using fromEntries() and entires() is that the object format we get there is already a lookup optimized object, so we don't always need to convert it to a Map, when we need to only read, object will be very fast, I assume its gonna be only slow when we modify it, so we kinda end up having a choice out of the box.

But also lets consider what's best for the database and types

**Comment by kof** [comment]
Ok Array.from is 2-3x faster than Object.fromEntries(temp1.entries()) which is kinda expected

**Comment by kof** [comment]
More perf tests on m1 max:
I prepared a Map of 200k instances 
console.time('test')
JSON.stringify(Array.from(map200k))
console.timeEnd('test')

Which logs 60-100ms, stringified its 6.7mb of data so just getting that file in to a Map will cost us several hundreds of milliseconds on a weaker machine than my m1 max

**Comment by kof** [comment]
Another test with objects: 

```
const object200k =  Object.fromEntries(map200k.entries())
console.time('test')
JSON.stringify(object200k)
console.timeEnd('test')
```

same dataset, same timing, I think most of the time is spent in JSON.stringify()

Lets just hope there is never a single page that has 200k instances

**Comment by kof** [comment]
JSON.parse on 200k objects from array is equally slow/fast. So the bottleneck with this size of a tree is always going to be JSON.parse/serialize if we use Array.from() and new Map() ...

**Comment by kof** [comment]
I wonder what the perf will be if we put the objects as separate entries in the db, which in the end is probably the best anyway, but we also need to take out the cssRules out of instances

**Comment by kof** [comment]
neat: 

```js
const map = new Map([[key, value]])
const arr = [...map] 
```

**Comment by rpominov** [comment]
I think the data structure should be evaluated based on operations that we have in https://github.com/webstudio-is/webstudio-designer/tree/main/packages/project/src/shared/tree-utils

Most important read operations seem to be:

- findInstanceById
- findParentInstance
- getInstancePath / getInstancePathWithPositions
- getInstanceChildren (not implemented as it's just `instance.children` currently)

Write operations (Not as important in terms of performance, as they shouldn't be frequent. But things like patch size or collaboration can be important):

- deleteInstance
- insertInstance
- reparentInstance
- setInstanceChildren (used rich text editor)

---------------------------------------------------

For `Map<instanceId, {id, component, children: ['id1', 'id2'] ...}>`:

- findInstanceById (much faster)
- findParentInstance (same?)
- getInstancePath / getInstancePathWithPositions (slower?)
- getInstanceChildren (~same)

**Comment by kof** [comment]
@rpominov definitely and in our new proposal we actually have a problem with finding parents, since there is now no way to traverse the tree from child to the root and that's needed for a lot of these utils.

To find parents now we have to get each instance and check if the our child is in their children, it's a full scan. Right now with tree we do full scan for findById until we find it, then we have the parents for free since we memorized the path.

Seems like we almost need to have both data structures to have all operations fast ...

**Comment by kof** [comment]
Makes me think right now that for our tree manipulations, to keep the performance optimized always, we will need different indexes, just like a database, for different operations.

Basically it makes sense to have  a stateful class that would hold all the data and provide all those functions as methods.
This way we can have various indexes in that class in sync and we can add new methods and optimize them any time.

It would be an OOP approach.

If we need multiple indexes and we keep the current functional approach, we run into risk of having the indexes not correctly updated in different cases, since we would have to maintain them as separate objects and wire up the updates correctly.

**Comment by kof** [comment]
Something like:
```
const tree = new InstanceTree(array)
tree.findInstanceById(...)
tree.findParentInstance(...)
tree.getInstancePath(...)
```

**Comment by rpominov** [comment]
> To find parents now we have to get each instance and check if the our child is in their children

This seem ~= to what we do currently: look at each node in tree until you find one with the right instance in children.

The difference is when you need all parents (path), currently we get it for free after we find the closest parent, but in the new structure we'll have to scan again and again.

> Makes me think right now that for our tree manipulations, to keep the performance optimized always, we will need different indexes, just like a database, for different operations.

Yes, was thinking that too.

A class sounds good to me.

-----------------------------------------------------

Another question: should we actually change serialised representation? The one we:
- store in DB
- send as JSON from server to client
- send as JSON from/to iframe
- keep as JSON in `clipboardData` for copy/paste

Maybe current one is fine actually? I think some of requirements for this representation are:

- compactness: we're making it slightly worse with `array` and `{type: text}`
- correctness: current one guarantees that it's a correct tree with no loops or detached branches
- speed of converting between representations: array is better as discussed above
- ability to store a branch of a tree using the same data-structure (e.g. for copy/paste): trivial now, possible with array too

**Comment by kof** [comment]
> This seem ~= to what we do currently: look at each node in tree until you find one with the right instance in children.

yes, its a full scan just to find the instance by id, but getting parents in this case is essentially free.

**Comment by TrySound** [comment]
> It would be an OOP approach.

Or it can be an type and a set of utilities around this type, no need classes, they are not minified well.

**Comment by kof** [comment]
Another point is how we are going to store that in the future and how we can update things without reading the full tree.

Ultimately flat array of instances can be easily stored in a tabled and scanned on the server for specific instance updates. Even reparenting would be a matter of finding source and destination instance and placing the child id in the right position in children.

That is if we think we will be translating the changes to a flat table at some point.

**Comment by kof** [comment]
> > It would be an OOP approach.
> 
> Or it can be an type and a set of utilities around this type, no need classes, they are not minified well.

I feel like modification is not a concern at all, since you will never have the need to reduce the amount of methods you can run on that data structure and they are anyways quite limited to what we need to do.

**Comment by kof** [comment]
How would you do an FP thing that guarantees updating all indexes at the right operations? You would eventually have to have each method take each index and it would have to update each index it affects.

**Comment by kof** [comment]
Another thought:  if we don't know for sure what data structure we will need in the future, we can as well start with implementing the abstraction with indexes that makes all utils fast and keep data in the database as-is until we know the new format.

Basically we can make the format we save it in the database in irrelevant by creating that abstraction.

**Comment by kof** [comment]
> compactness: we're making it slightly worse with array and {type: text}

Yeah, the main advantage is not having to do typeof string check everywhere, its a more consistent type with instance and if we need more types, it will. make them more convenient to work with

**Comment by kof** [comment]
Interesting thing about having an array format is that it can be streamed, you can start rendering things as you fetch an array of things. In case an instance was loaded before a parent was loaded, it could wait until parent is loaded before rendering that instance.

This in return opens up for a possibility to render only a subset of the tree, for example when you want to render only whats in the viewport.

I think arrays are the best moving forward for large trees
