### ISSUE TITLE
CSSValueInput doesn't work as expected with esc key

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-designer#656]
As of now 1st ESC press do nothing, 2nd reset the field to an empty value.
Should be:
1. If the menu is open - close the menu
2. If the menu is not open reset to the initial control value

**Comment by kof** [comment]
1st ESC closes dropdowns when they are open. Bug is when there is nothing to close, first ESC should revert back to the value that was last saved (non-intermediate value)
