### ISSUE TITLE
Stop overwriting browser cmd+(+-) keyboard shortcut

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#658]
Problem with overwriting it is that it can't be used to zoom the interface itself, which is an important accessibility feature.
Figma decided to break it and I copied it initially, but I regret it.
The solution is to just support +- without modifiers and release cmd++-  to the browser.

**Comment by kof** [comment]
Figma also supports +- without modifiers in addition to with modifiers

**Comment by taylornowotny** [comment]
Sounds perfect to me 👍
