### ISSUE TITLE
Change multiple spacing values at the same time using scrub

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#668]
In the spacing UI user can change values using scrub:

<img width="260" alt="Screenshot 2022-12-20 at 15 11 40" src="https://user-images.githubusercontent.com/825702/208653569-cc3a9ecd-14fe-4c18-be8f-f6b7faca1a5d.png">

Special rules should apply when user holds OPTION/CONTROL:

<img width="278" alt="Screenshot 2022-12-20 at 15 06 35" src="https://user-images.githubusercontent.com/825702/208652712-5e13bb17-5771-4406-b447-c6a9d86d102c.png">

**Comment by kof** [comment]
I think this one is highly used at webflow

**Comment by rpominov** [comment]
Webflow uses SHIFT instead of CONTROL for changing 4 values.

I'd stick with what Webflow does because they probably have chosen the key carefully to avoid conflicts with some default behaviours in different browsers / operating systems.

@taylornowotny let me know if there's an important reason to use CONTROL when you're back at work, I'll go with SHIFT for now, but we can change later.

**Comment by taylornowotny** [comment]
Check again the Webflow behavior. There’s a way to change opposite values
and another way to change all 4 values. I’m away from my computer so I
forget which keys it is, but you can do both.

**Comment by kof** [comment]
Webflow uses shift to sync all 4 values, and alt to sync horizontal or vertical values

**Comment by rpominov** [comment]
Yes

> There’s a way to change opposite values

OPTION in our design and in Webflow

> and another way to change all 4 values

CONTROL in our design, but Webflow uses SHIFT

**Comment by rpominov** [comment]
> I forget which keys it is, but you can do both

I want to use only SHIFT for 4 values, unless there's a reason to use CONTROL

**Comment by taylornowotny** [comment]
Ok sounds good - let’s use the same keys as Webflow
