### ISSUE TITLE
Breakpoints panel suggests delete currently selected instead of specific breakpoint

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio-designer#691]
Here I clicked "delete tablet"

<img width="389" alt="image" src="https://user-images.githubusercontent.com/5635476/209430933-e8ef9d73-7c55-4274-b832-c6b75e5b06bf.png">

**Comment by kof** [comment]
You mean you selected a different breakpoint to delete, but it will delete the current breakpoint?

**Comment by kof** [comment]
Ah ok, only message is wrong, it deletes the breakpoint as expected.
