### ISSUE TITLE
Copy/paste instance across projects

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#72]
As a user I should be able to copy an instance and insert it in a different project .
If styles or properties use tokens, should those tokens also be imported? 
If so we first need an ability to resolve conflicts in tokens same way we need this for copy/pasting CSS from mini editor with tokens)

**Comment by kof** [comment]
@rpominov this one can close?

**Comment by rpominov** [comment]
Yes, but I didn't do anything with tokes

**Comment by kof** [comment]
yeah, this was done before tokens, so this part will be part of tokens task
