### ISSUE TITLE
Add "project" relation to DesignTokens

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-designer#743]
We need this for authorization checks. Also allows faster debug/find needed values.

https://github.com/webstudio-is/webstudio-designer/blob/62d870ad8e3da6ff95d4e6449971d3b843e87a62/packages/prisma-client/prisma/schema.prisma#L97

```
-- prisma
project   Project @relation(fields: [projectId], references: [id])
```

**Comment by TrySound** [comment]
DesignTokens no more
