### ISSUE TITLE
How will Tokens and Components work? Discussion

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#75]
We are thinking about using a 'components' and 'tokens' system to control styles of things instead of CSS classes (like Webflow uses).

First of all, nomenclature. If anyone has suggestions for improving this let me know. Temporarily I am calling:

static things on the canvas = elements
custom user-created components = components
an instance of a user-created component = instance
design token = token

What we are thinking so far:

- Elements can be styled individually. There will be no class or component applied at this point. The styles will just be set on the individual element.
- When an element is meant to be re-used multiple times, it can be made into a component. The component will contain the HTML element, the styles, and the properties. Instances of the component can be changed without necessarily changing the original. We will have to decide the best way to manage this. Variants? Instances? Override Fields? Let's talk more.
- Tokens on the other hand are good for re-using styles across multiple elements. For example, a user can configure a drop shadow on an element, then create a token for the drop shadow. They can then apply the token to any element and the drop shadow will be applied to that element.
- Components and Tokens will each have their own tab menu

This is obviously still in ideation stage, but we need to have some solution for managing styles for the beta. If it's not CSS classes, then we need to figure this out instead

**Comment by kof** [comment]
@taylornowotny  I am closing this issue, since we have discussed majority of this yesterday and will create a new one that summarizes the discussion
