### ISSUE TITLE
Undo stopped working when css value input is still focused

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#755]
After applying some style change from css value input try to hit cmd+z - it won't work. Unfocus the input and try again - it works.

**Comment by TrySound** [comment]
Looks like it's because of builtin text input history. Value is changed but not applied, more like entered new value but not pressed enter.

**Comment by TrySound** [comment]
We have the same behaviour in lexical editor. Maybe no need to override UX?

**Comment by kof** [comment]
Doesn't even change the value back atm, not sure why, ideally would be to keep it natively functional if it doesn't break anything, not sure why we broke it in the first place

**Comment by TrySound** [comment]
Found, our hotkeys are a bit messy
