### ISSUE TITLE
Clone databases for the new SaaS version

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio-designer#763]
~~In Supabase, clone the following database for the new SaaS deployments. ~~
~~Data will be copied (again) before switching to these databases.~~

~~Webstudio Dev -> SaaS Webstudio Dev~~
~~Webstudio Prod (US) ->  SaaS Webstudio Prod~~

In Supabase, create a new database for OSS Webstudio. The currently used databases will stay and will be the SaaS version, so we do not need to migrate data.

1. Create a new database: `OSS Webstudio Dev` and clone data.
2. Rename databases:
- Webstudio Dev -> SaaS Webstudio Dev
- Webstudio Prod (US) -> SaaS Webstudio Prod (US)

**Comment by kof** [comment]
We only need to rename current prod, dev doesn't need prod data
