### ISSUE TITLE
Make Sizing & Spacing generic tokens

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#769]
<img width="386" alt="Screenshot 2023-01-11 at 12 05 50 PM" src="https://user-images.githubusercontent.com/86495896/211906906-28197e55-988a-4e6f-93c1-c6570b3bccf2.png">
<img width="238" alt="Screenshot 2023-01-11 at 12 06 06 PM" src="https://user-images.githubusercontent.com/86495896/211906981-966cb136-ee47-42b5-9850-7d97df9e1fe0.png">

We have a **Sizing & Spacing** scale in the **Design Docs** (in the **Style & Tokens** page) but these will not be made into tokens via the **Tokens Studio for Figma** plugin. The plugin does not support generic tokens, which are the best solution for sizing & spacing. 

The engineering team will have to make generic tokens out of these values in code. These tokens will not be represented in figma or in the plugin, but size & spacing values in the design will almost always conform to the values in the scale. It's very unlikely that any of these values will change because it's a fairly big scale.

Let me know if you have questions, thanks.

**Comment by kof** [comment]
I already added them to the design system and we are using them everywhere, might be occasionally using the wrong value for sure, needs to be checked per component basis

**Comment by taylornowotny** [comment]
Great! This is resolved then
