### ISSUE TITLE
Migrate to monorepo setup

### ISSUE THREAD

**Issue by okonet** [webstudio-is/webstudio-designer#78]
Currently, it's [quite painful to work on SDK and designer at the same time](https://github.com/webstudio-is/webstudio/blob/main/docs/contributing.md#develop-designer-and-sdk-in-parallel) and it will be harder over time with more packages (CLI etc) that share code. I propose we move towards monorepo asap to avoid this pain.

## Requirements

1. Ability to work on multiple parts of the project without the need to setup anything
2. Shared code that just works: types, imports from packages, jump to definition, refactoring, etc.
4. Multiple apps should be allowed
5. It should be _fast_ to develop, create new packages
6. Each public package should have it's own versioning (I propose we adopt https://github.com/changesets right away with this move)

I'd go with https://turborepo.org or https://nx.dev where I'm more biased towards turborepo because it integrates nicely with Vercel but I'd research both (or other alternatives).

**Comment by kof** [comment]
I would also consider keeping the sdk repo too, but only the primitive components or stuff that a user would need to provide when they create their own SDK. So that they can basically  fork the repo and start changing it, without thinking how to extract a folder from monorepo and set it all up.

A huge problem we need to solve with SDK is making it easy for a developer to create own sdk

**Comment by okonet** [comment]
I would disagree with this. To me, SDK is just a package in a monorepo setup. I would even propose to move everything into one big monorepo now:

```
webstudio
├── apps
 │        ├─ designer
└── packages
          ├─cli
          ├─design-system
          ├─sdk
```

For third-party SDKs we could consider creating a template repo so it's easy to start but it will probably live in another org/repo anyways.

Alternatively, it should be as easy to create an SDK in the monorepo (thus, `It should be fast to develop, create new packages`).

**Comment by kof** [comment]
Yeah, I am not super sure what I suggested above is the best way to go since we don't have a clear understanding how a user will create own SDK and what would be the best DX there.

So  if you have strong feelings about moving SDK into a monorepo package - ok, lets go for it.

**Comment by kof** [comment]
As a next step we would need to split it in a number of monorepo packages, so that we have in the end that final small package that just represents user-based sdk

**Comment by okonet** [comment]
Yeah I think we should optimize for speed of development and contribution DX until we know how SDK actually will look like. With a monorepo we can move things around effortlessly and there is a lot of shared code already which will be extracted and reused.

**Comment by kof** [comment]
Follow up issue https://github.com/webstudio-is/webstudio-designer/issues/138
