### ISSUE TITLE
Implement undo/redo

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#8]
Not sure we even need the undo/redo icon buttons, Figma has none and it seems fine, everybody knows that shortcut 

- [x] delete instance
- [x] insert instance
- [x] reparent instance
- [x] update styles
- [x] update props
- [x] delete prop
- [x] update children

**Comment by smotched** [comment]
Yeah, I'm not a fan of having a lot of icons at the top, and undo redo its pretty ingrained. The only issue might be on something like iPad or any other touch based device.

**Comment by kof** [comment]
Hmm, yeah, though ipad is a quite a different beast, it would need a lot of special things. I am not sure if we should be optimizing for it at this stage.

**Comment by kof** [comment]
Also undo/redo could be in the dropdown menu, harder to access, but still available

**Comment by kof** [comment]
I have just finished the prototype of a sync engine that uses patches to send updates across the application and to the server. The same engine can do undo/redo functionality, I did it for instance deletion only for now, feel free to try it out!

**Comment by kof** [comment]
Inserting instances now also on transactions, so undo/redo just works

**Comment by smotched** [comment]
There's an issue where the first instance of undo doesn't work until the item is unselected

**Comment by kof** [comment]
Fixed @smotched

**Comment by kof** [comment]
Ok now reparenting (moving existing element) should be undoable too

**Comment by kof** [comment]
Updating styles with undo/redo is now implemented

**Comment by kof** [comment]
It is implemented 🎉

Now all actions are undo/redo -able! Please let me know if you spot any bugs!

**Comment by smotched** [comment]
Hmm, seems like you have to click away from the element and click back in for the values you _undo_ to update in the right sidebar

**Comment by smotched** [comment]
@kof Hmm, seems like you have to click away from the element and click back in for the values you undo to update in the right sidebar

**Comment by smotched** [comment]
@kof Hmm, seems like you have to click away from the element and click back in for the values you _undo_ to update in the right sidebar
