### ISSUE TITLE
Popover component

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#824]
This new component is based on the radix popover. It will usually be triggered by a button, but might also be triggered by an icon button.

The component is organized a little weirdly in figma, to get around some figma layout limitations. However you achieve the layout is up to you as long as all the spacing is exactly the same as the design.

See documentation in the Webstudio Library file: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=0%3A1&t=4NG0ZJnGoHcrI26W-1

<img width="237" alt="Screenshot 2023-01-20 at 1 38 40 PM" src="https://user-images.githubusercontent.com/86495896/213809888-ecdf5f8a-7f39-49d4-964e-b0c7dcfa37ab.png">
<img width="566" alt="Screenshot 2023-01-20 at 1 39 34 PM" src="https://user-images.githubusercontent.com/86495896/213809993-de8e4072-fcfd-4763-85d7-155a2a75fbea.png">

**Comment by kof** [comment]
@rpominov I just realized we have PopoverHeader in Popover, which is wrong, we should move that to FloatingPanel and align both with Figma

**Comment by rpominov** [comment]
> @rpominov I just realized we have PopoverHeader in Popover, which is wrong, we should move that to FloatingPanel and align both with Figma

Yes, PopoverHeader implements "Title" https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=2%3A12361&t=1OBA8HVLN3wYuhei-0

<img width="413" alt="Screenshot 2023-01-27 at 11 15 31" src="https://user-images.githubusercontent.com/825702/215029733-9609533f-9165-47f5-9dc2-468828d729ba.png">

And we have another "Title" implementation here: https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/app/designer/features/sidebar-left/lib/header.tsx

I'm sorting this out in https://github.com/webstudio-is/webstudio-designer/pull/857
