### ISSUE TITLE
Dialog component

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#831]
We started using dialog for dashboard, so we now need to create a figma component and then a design system component.

**Comment by markxtang** [comment]
Created the component in the Library Figma, and added documentation in the Docs>Dashboard Figma.

**Comment by rpominov** [comment]
@kof says you've decided not to have a Dialog component in Figma after all.

In code we still need to customise [Radix's Dialog](https://www.radix-ui.com/docs/primitives/components/dialog) according to some design. I've noticed you have a Floating Panel component which looks exactly like Dialog in the dashboard design:

<img width="337" alt="Screenshot 2023-01-26 at 10 21 07" src="https://user-images.githubusercontent.com/825702/214770575-71c75181-0c81-40a8-9da9-4cba97f8fa49.png">

I'm going to use Floating Panel to style Radix's Dialog

**Comment by markxtang** [comment]
@rpominov sorry about the confusion. Yes, the intention is to have the dialog look the same as the Floating Panel. I will update the docs with that info. Thanks for making it!
