### ISSUE TITLE
Figure out how to handle line-height

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#837]
It seems like browsers may position text differently when `line-hight` is not equal to `font-size`: https://stackoverflow.com/questions/4474636/is-it-possible-to-achieve-line-height-consistency-in-all-browsers

We need to understand whether this the case for us, and if yes, decide what to do about it.

**Comment by rpominov** [comment]
There seem to be no issue with line-heigh. I've tested Chrome 109, Firefox 109, Safari 16.1, and Figma: they all treat `line-height` the same:

<img width="1392" alt="Frame 1" src="https://user-images.githubusercontent.com/825702/214265665-3831d2c3-63eb-4ce6-b627-6465c684b4df.png">

Also, [this article](https://www.figma.com/blog/line-height-changes/) says that Figma should treat line-height same as the browsers: 
<img width="708" alt="Screenshot 2023-01-24 at 14 17 45" src="https://user-images.githubusercontent.com/825702/214266234-14639c64-400f-425e-926a-378251093aa9.png">

So, I think we should just use `line-height`s defined in Figma.

**Comment by rpominov** [comment]
Code of the line-height test, in case we ever need it:

```ts
import { typography as figmaTypography } from "../__generated__/figma-design-tokens";

const LineHeightTest = () => {
  const fontFamilies = [
    ...new Set(Object.values(figmaTypography).map((t) => t.fontFamily)),
  ];
  const fontSizes = [8, 13, 16, 32];
  const combinations = fontSizes.flatMap((fontSize) => [
    { fontSize: `${fontSize}px`, lineHeight: `${fontSize}px` },
    {
      fontSize: `${fontSize}px`,
      lineHeight: `${Math.round(fontSize * 1.2)}px`,
    },
    {
      fontSize: `${fontSize}px`,
      lineHeight: `${Math.round(fontSize * 1.5)}px`,
    },
    { fontSize: `${fontSize}px`, lineHeight: `${Math.round(fontSize * 2)}px` },
  ]);

  return (
    <table className={typography.regular()} style={{ border: "dashed 1px" }}>
      <thead>
        <tr>
          <th></th>
          {fontFamilies.map((fontFamily) => {
            const name = fontFamily.split(",")[0];
            return <th key={name}>{name}</th>;
          })}
        </tr>
      </thead>
      <tbody>
        {combinations.map((combination) => {
          const name = `${combination.fontSize} / ${combination.lineHeight}`;
          return (
            <tr key={name}>
              <th>{name}</th>
              {fontFamilies.map((fontFamily) => (
                <td key={name + fontFamily}>
                  <div
                    style={{ fontFamily, background: "pink", ...combination }}
                  >
                    Abgl1
                  </div>
                </td>
              ))}
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};
```

**Comment by rpominov** [comment]
After looking more close I've noticed some very small like half a pixel differences. Still think it's better to live with them than having complicated rules for designers and developers on how to use `line-height`s

**Comment by kof** [comment]
cool, lets go with this, then, subpixel differences shouldn't matter in case of text
