### ISSUE TITLE
Decide on what to use for toasts

### ISSUE THREAD

**Issue by SaraVieira** [webstudio-is/webstudio-designer#85]
For many things including error and success messages, we will need to use toasts. I think creating our own library will just be reinventing the wheel and for that, I think the best package I have used so far has been: 
https://react-hot-toast.com/

I used it just as plug and play and also at Remote I have used it and matched it to our design system and it works super well. One major plus is that it accepts promises

Would love to hear options and ideas

**Comment by kof** [comment]
This one seems good, only complain I have is build-in styling lib even though its very small
Seems like all styles can be overwritten

**Comment by kof** [comment]
@okonet  I bet you have opinions on this one or maybe even a suggestion

**Comment by okonet** [comment]
As discussed on Discord, I'm fine with this lib since the API they use is signed with how I'd do it. One thing we should do though is re-export it from design-system and not use directly in code. This will allow us to switch the library in the future.

**Comment by okonet** [comment]
@SaraVieira BTW have you tried https://www.radix-ui.com/docs/primitives/components/toast? I think it would be better to stick to one lib if possible. What's is missing from this one?

**Comment by kof** [comment]
@okonet oh shit I didn't know radix has already a toast!!! I think its new

**Comment by SaraVieira** [comment]
Hmmm, we would end up having to use both or make our own JS implementation because their API is does not have anything to show the toasts, it's just the UI

**Comment by okonet** [comment]
Yeah that's what I meant that I would need to add the API for that later. But let's integrate react-hot-toast to not block us. We can revisit later.

**Comment by kof** [comment]
@SaraVieira what is radix-ui toast missing?

**Comment by SaraVieira** [comment]
I'll make something

**Comment by kof** [comment]
@SaraVieira Lets close this since this issue was about the research and create an implementation issue

**Comment by SaraVieira** [comment]
Closed
