### ISSUE TITLE
Session maintained when user no longer exists 

### ISSUE THREAD

**Issue by SaraVieira** [webstudio-is/webstudio-designer#92]
When a user is deleted or we drop the database if we are still logged in their session stays and we get an error for a Postgres constrain since it's trying to create a project with a user id that does not exist 

To reproduce 
1. login
2. drop database
3. go to dashboard, create project

Possible solution

When loading up the dashboard check if the user is logged in and if the user exists, if the user does not exist logout the user and redirect to the login page

**Comment by kof** [comment]
Done?
