### ISSUE TITLE
New icons needed

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#94]
I've got this covered but it will be a while before I can get to it.

Currently we are using a mix of icons from various sources. Due to the unique nature of our product we will need to create custom icons because no one library meets our needs.

For look & feel I am planning to copy the general style of this icon set: https://www.untitledui.com/icons 
very similar to Radix icons but a much larger library. Will copy as much as I can to save time.

**Comment by kof** [comment]
Currently majority of icons we use are https://icons.radix-ui.com/

Some are from https://fonts.google.com/icons?selected=Material+Icons

Those icons you see in this list are from material ui https://github.com/webstudio-is/webstudio-designer/tree/main/app/shared/icons

**Comment by kof** [comment]
seems like we are adding icons from figma as we go, no need for separate issue
