### ISSUE TITLE
Remove GitHub login from PR branches 

### ISSUE THREAD

**Issue by SaraVieira** [webstudio-is/webstudio-designer#96]
Because of callback url limitations the GitHub login does not work in PR branches and for that reason we should have the button disabled with a tooltip explaining why 
We can use the vercel environment variable for this

**Comment by kof** [comment]
Or maybe show some error that explains it? because not showing the UI at all won't let you at least see the UI the way it is on prod

**Comment by SaraVieira** [comment]
Updated the issue
