### ISSUE TITLE
New Component: Two Rows Small Icon Button Container

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-designer#979]
This UI gives the user a way to affect two rows with one small icon button. 
  e.g. When a user needs to delete a Name and Value pair when the Name and Value are on different rows.  It is essentially just a container for the small icon button component.
  
  Please pay careful attention to the layout so everything aligns in the same way as the design. 
  
<img width="394" alt="Screenshot 2023-02-09 at 12 48 31 PM" src="https://user-images.githubusercontent.com/86495896/217936494-f60b0567-e495-4367-8900-b1371c98490a.png">

Example:
<img width="461" alt="Screenshot 2023-02-09 at 12 52 46 PM" src="https://user-images.githubusercontent.com/86495896/217936590-907cc2cf-8da0-4a9a-8d18-95cc05944e15.png">
<img width="688" alt="Screenshot 2023-02-09 at 12 53 02 PM" src="https://user-images.githubusercontent.com/86495896/217936644-78b91374-2727-4dcb-aa47-1d55909a57f8.png">

**Comment by rpominov** [comment]
Forgot to link PR: #987
