### ISSUE TITLE
GDPR compliant tracking of visitors and installations

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#98]
1. We need a way to learn how users use webstudio.is service (anonymously) that is fully GDPR compliant and doesn't require cookie banners.
2. We need to know how many people install webstudio on their machines/servers and which version they are using. This is going to help understand in the future when and how to make breaking changes.

**Comment by kof** [comment]
Cloudflare's analytics looks good

**Comment by andrasbacsai** [comment]
Cloudflare Analytics is good! 

At the moment, we could only use the client based analytics, as we are still deploying to Vercel.

Should I set it up?

**Comment by kof** [comment]
What about the workers? Doesn't work there?

**Comment by andrasbacsai** [comment]
Workers have analytics, but not as detailed as for sites.

**Comment by andrasbacsai** [comment]
Cloudflare analytics enabled.
